---
- name: "Import checks task"
  ansible.builtin.import_tasks: checks.yml
  tags:
    - gitlab_runner
    - checks

- name: "Import gitlab-runner task"
  ansible.builtin.import_tasks: gitlab-runner.yml
  become: true
  tags: gitlab_runner
