---
- name: Setup apache firewalld rules
  ansible.posix.firewalld:
    zone: "{{ item[0].zone }}"
    service: "{{ item[1] }}"
    state: "{{ item[0].state }}"
    permanent: true
    immediate: true
  with_nested:
    - "{{ apache_firewalld_zones }}"
    - ["http", "https"]
