---
galaxy_info:
  role_name: proxmox
  author: Libre Logic
  description: Proxmox VE configuration
  license: GPL-3.0
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - proxmox
    - virtualization
    - hypervisor
    - kvm
    - lxc
    - vm

dependencies: []
#  - nodiscc.xsrv.common # optional, unattended upgrades
