---
# @tag monitoring - setup monitoring/alerting/logging system/utilities

galaxy_info:
  role_name: monitoring
  author: "nodiscc <nodiscc@gmail.com>"
  description: "monitoring, alerting, audit and logging system"
  license: GPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "11"
        - "12"
  galaxy_tags:
    - system
    - performance
    - monitoring
    - alerting
    - health
    - graphs
    - charts
    - syslog
    - rsyslog
    - logging
    - audit
    - security
dependencies:
  - librelogic.librelogic.handlers
  - librelogic.librelogic.monitoring_rsyslog
  - librelogic.librelogic.monitoring_netdata
  - librelogic.librelogic.monitoring_utils
