---
- name: Copy fail2ban jail configuration for proxmox
  ansible.builtin.template:
    src: etc_fail2ban_jail.d_proxmox.conf.j2
    dest: /etc/fail2ban/jail.d/proxmox.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload fail2ban

- name: Copy fail2ban filter for proxmox authentication failures
  ansible.builtin.template:
    src: etc_fail2ban_filter.d_proxmox.conf.j2
    dest: /etc/fail2ban/filter.d/proxmox.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload fail2ban
