---
galaxy_info:
  license: "GPL-3.0"
  author: "Libre Logic <contact@libre-logic.fr>"
  description: "Simple SMTP server/mail interceptor and web interface"
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - 18.04

dependencies:
  - librelogic.librelogic.apache
