---
galaxy_info:
  license: "GPL-3.0"
  author: "Libre Logic <contact@libre-logic.fr>"
  description: "Database management in a single PHP file"
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - 10
    - name: Ubuntu
      versions:
        - 18.04

dependencies:
  - nodiscc.xsrv.apache
