---
galaxy_info:
  role_name: openldap
  author: "nodiscc <nodiscc@gmail.com>, Libre Logic <contact@libre-logic.fr>"
  description: "LDAP directory server and web management tools"
  license: "GPL-3.0"
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - 10
        - 11
  galaxy_tags:
    - ldap
    - directory
    - authentication
dependencies: []
  #- 'librelogic.librelogic.common' # optional, base system setup/hardening/firewall/bruteforce protection
  #- 'librelogic.librelogic.apache' # optional, if ldap-account-manager/self-service-password setup is enabled
  #- 'librelogic.librelogic.php_fpm' # optional, if ldap-account-manager/self-service-password setup is enabled
