---
- name: Create ansible facts.d directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"

- name: Create netdata fact file
  ansible.builtin.template:
    src: etc_ansible_facts.d_netdata.fact.j2
    dest: /etc/ansible/facts.d/netdata.fact
    mode: "0644"
  notify: update ansible facts
  ignore_errors: "{{ ansible_check_mode }}"
