---
- name: Copy netdata firewalld service definition
  ansible.builtin.template:
    src: etc_firewalld_services_netdata.xml.j2
    dest: /etc/firewalld/services/netdata.xml
    owner: root
    group: adm
    mode: "0640"
  notify: reload firewalld
  ignore_errors: "{{ ansible_check_mode }}"

# reload firewalld service definitions
- name: Apply configuration (flush handlers)
  ansible.builtin.meta: flush_handlers
- name: Setup firewalld rules for netdata
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    service: netdata
    state: "{{ item.state }}"
    permanent: true
    immediate: true
  with_items: "{{ netdata_firewalld_zones }}"
  ignore_errors: "{{ ansible_check_mode }}"
