---
##### SSL/TLS CERTIFICATES - SELF-SIGNED #####

- name: Install requirements for SSL/TLS certificates generation
  ansible.builtin.apt:
    state: present
    package:
      - python3-openssl
      - ssl-cert

- name: Generate openssl private key
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/private/{{ adminer_fqdn }}.key"
  notify: restart apache
  ignore_errors: "{{ ansible_check_mode }}"

- name: Generate openssl certificate signing request
  community.crypto.openssl_csr:
    path: "/etc/ssl/private/{{ adminer_fqdn }}.csr"
    privatekey_path: "/etc/ssl/private/{{ adminer_fqdn }}.key"
    common_name: "{{ adminer_fqdn }}"
    key_usage: "digitalSignature,keyEncipherment"
    basicConstraints: "CA:TRUE"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Generate self-signed openssl certificate
  community.crypto.x509_certificate:
    path: "/etc/ssl/certs/{{ adminer_fqdn }}.crt"
    privatekey_path: "/etc/ssl/private/{{ adminer_fqdn }}.key"
    csr_path: "/etc/ssl/private/{{ adminer_fqdn }}.csr"
    provider: selfsigned
  notify: restart apache
  ignore_errors: "{{ ansible_check_mode }}"
