---
galaxy_info:
  role_name: docker
  author: "geerlingguy, nodiscc <nodiscc@gmail.com>, Libre Logic <contact@libre-logic.fr>"
  description: "Open source application containerization technology"
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
    - name: Ubuntu
      versions:
        - 18.04
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
dependencies:
  - librelogic.librelogic.handlers
  # - librelogic.librelogic.common # optional
  # - librelogic.librelogic.monitoring # optional
